version: '2'
services:
    front:
        build: .
        container_name: topkekapp
        volumes:
            - .:/var/www/html/
        ports:
            - "8888:80"
        labels:
            - traefik.enable=true
        depends_on:
            - mysql
    mysql:
        image: mysql:5
        environment:
            - "MYSQL_DATABASE=library"
            - "MYSQL_ROOT_PASSWORD=topkek"
            - "MYSQL_USER=top"
            - "MYSQL_PASSWORD=kek"

