version: '2'
services:
    front:
        build: .
        container_name: epub-reader
        volumes:
            - .:/var/www/html/
            - ./php-ini:/usr/local/etc/php/custom.d
        environment:
            PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
        ports:
            - "8888:80"
        depends_on:
            - mysql
    mysql:
        image: mysql:5
        environment:
            - "MYSQL_DATABASE=library"
            - "MYSQL_ROOT_PASSWORD=topkek"
            - "MYSQL_USER=top"
            - "MYSQL_PASSWORD=kek"
        ports:
            - "3306:3306"
